first commit

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,10 +9,12 @@ env:
   ECR_REPO: monitor-web
   ECS_CLUSTER: monitoring-cluster
   ECS_SERVICE: monitor-web
+  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
 
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -29,8 +31,15 @@ jobs:
 
       - name: Ensure ECR repo exists and get URI
         id: ecr
-        run: | 
-          set -e aws configure set default.region "${{ env.AWS_REGION }}" REPO_NAME="${{ env.ECR_REPO }}" if ! aws ecr describe-repositories --repository-names "$REPO_NAME" > /dev/null 2>&1; then echo "Repository $REPO_NAME not found — creating" aws ecr create-repository --repository-name "$REPO_NAME" >/dev/null fi REPO_URI=$(aws ecr describe-repositories --repository-names "$REPO_NAME" --query 'repositories[0].repositoryUri' --output text) echo "repo_uri=$REPO_URI" >> $GITHUB_OUTPUT
+        run: |
+          set -e
+          REPO_NAME="${{ env.ECR_REPO }}"
+          if ! aws ecr describe-repositories --repository-names "$REPO_NAME" > /dev/null 2>&1; then
+            echo "Repository $REPO_NAME not found — creating"
+            aws ecr create-repository --repository-name "$REPO_NAME" >/dev/null
+          fi
+          REPO_URI=$(aws ecr describe-repositories --repository-names "$REPO_NAME" --query 'repositories[0].repositoryUri' --output text)
+          echo "repo_uri=$REPO_URI" >> $GITHUB_OUTPUT
 
       - name: Build Docker image
         run: |
